### ISSUE TITLE
Check shortcode definitions: controller resolvable?

### ISSUE THREAD

**Issue by MalteWunsch** [webfactory/WebfactoryShortcodeBundle#24]
It would be nice to have an easy way to test (either explicitly or implicitely) if the shortcode definitions are valid. The semantic configuration in #21 does a lot for that, but does not check whether a controller can be resolved.

`\Symfony\Component\HttpKernel\Controller\ControllerResolver` might help.

**Comment by mpdude** [comment]
`ShortcodeDefinitionTestHelper` from #23 does that. For an example, see the test that tests the TestHelper:

https://github.com/webfactory/WebfactoryShortcodeBundle/blob/a5e08c58c8a3ae150f399b0c0f13973bfacdc1c4/tests/Functional/ShortcodeDefinitionTestHelperTest.php
